package handlers

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"testing"

	"github.com/nodealchemy/powernode-system/agent/internal/lifecycle"
	"github.com/nodealchemy/powernode-system/agent/internal/manifest"
	"github.com/nodealchemy/powernode-system/agent/internal/mount"
	"github.com/nodealchemy/powernode-system/agent/internal/runtime/tasks"
	"github.com/nodealchemy/powernode-system/agent/internal/systemd"
	"github.com/nodealchemy/powernode-system/agent/internal/taskguard"
)

// The lifecycle handler takes task.Options["unit"] into `systemctl <verb>`
// as root. The node API serves EVERY pending task on the instance to the
// agent (NodeApi::StatusController#pending_tasks has no agent_delegated?
// filter) and TasksController#create permits options: {} as free-form JSONB,
// so the unit name is attacker-choosable by any principal holding
// system.infra_tasks.create — including an AI agent, because the
// system.task.* rows are seeded with ai_agent_id nil and
// Ai::InterventionPolicy#agent_matches? admits that.
//
// The rule is composed in validateUnit: taskguard.UnitName (one component,
// ".service"), taskguard.NamePrefix ("powernode-"), taskguard.InstalledUnit
// (a regular file of that exact name in lifecycle.UnitDir()). Each refusal
// fixture below is crafted so that exactly ONE of the three refuses it, so a
// mutation that disables a rule leaves a red example naming it.

func lifecycleUnitDir(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	t.Setenv("POWERNODE_LIFECYCLE_UNIT_DIR", dir)
	return dir
}

func writeUnitFile(t *testing.T, dir, name string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte("[Unit]\nDescription=fixture\n"), 0o644); err != nil {
		t.Fatal(err)
	}
}

func lifecycleTask(options map[string]any) *tasks.Task {
	return &tasks.Task{ID: "t1", Command: "restart", Options: options}
}

func TestLifecycleRefusesUnitsOutsideTheModuleGeneratedSet(t *testing.T) {
	dir := lifecycleUnitDir(t)
	// Units that really are present in /etc/systemd/system on a node but were
	// not generated by lifecycle.AttachServices: an operator-installed service
	// and a storage mount unit (System::Storage::TaskPayloadBuilder emits
	// powernode-storage-<path>.mount into the same directory).
	writeUnitFile(t, dir, "nginx.service")
	writeUnitFile(t, dir, "powernode-storage-mnt-data.mount")
	if err := os.Symlink(filepath.Join(dir, "nginx.service"), filepath.Join(dir, "powernode-m-link.service")); err != nil {
		t.Fatal(err)
	}
	// A real unit file OUTSIDE the unit directory, reachable by traversal.
	// t.TempDir() nests every dir for one test under one parent, so the
	// relative hop below resolves to an existing regular file — which is what
	// makes this case isolate UnitName: InstalledUnit alone would accept it.
	outside := t.TempDir()
	writeUnitFile(t, outside, "powernode-m-evil.service")
	traversal := filepath.Join("..", filepath.Base(outside), "powernode-m-evil.service")

	cases := map[string]any{
		"traversal to a real file (UnitName)":        traversal,
		"present, no powernode- prefix (NamePrefix)": "nginx.service",
		"present, .mount suffix (UnitName suffix)":   "powernode-storage-mnt-data.mount",
		"symlink of the right name (InstalledUnit)":  "powernode-m-link.service",
		"absent from the unit dir (InstalledUnit)":   "powernode-019f7cb5-3858-7caa-aa9f-51629dc8e573-rails.service",
		"agent's own unit (InstalledUnit)":           "powernode-agent.service",
		"distro unit (NamePrefix)":                   "sshd.service",
		"newline (UnitName)":                         "powernode-m-x.service\nExecStart=/bin/sh",
		"empty (UnitName)":                           "",
		"not a string":                               42,
	}
	for _, verb := range []systemd.ActionVerb{systemd.Start, systemd.Stop, systemd.Restart} {
		for name, unit := range cases {
			rec := &mount.RecorderRunner{}
			h := &LifecycleHandler{deps: tasks.Dependencies{MountRunner: rec}, verb: verb}
			_, err := h.Execute(context.Background(), lifecycleTask(map[string]any{"unit": unit}))
			if !errors.Is(err, taskguard.ErrRefused) {
				t.Errorf("%s %s: expected ErrRefused, got %v", verb, name, err)
			}
			// Nothing reaches systemctl — not even the idempotency probe
			// (`is-active`) that start/stop run first.
			if len(rec.Invocations) != 0 {
				t.Errorf("%s %s: expected no actuation after refusal, got %+v", verb, name, rec.Invocations)
			}
		}
	}
}

// Absent and zero-valued options are refused, not defaulted: a sibling
// iteration found an equality oracle that missed a default entirely.
func TestLifecycleRefusesAbsentUnit(t *testing.T) {
	lifecycleUnitDir(t)
	for name, options := range map[string]map[string]any{
		"nil options": nil,
		"no unit key": {"scope": "unit"},
		"unit nil":    {"unit": nil},
		"unit empty":  {"unit": ""},
	} {
		rec := &mount.RecorderRunner{}
		h := &LifecycleHandler{deps: tasks.Dependencies{MountRunner: rec}, verb: systemd.Restart}
		_, err := h.Execute(context.Background(), lifecycleTask(options))
		if !errors.Is(err, taskguard.ErrRefused) {
			t.Errorf("%s: expected ErrRefused, got %v", name, err)
		}
		if len(rec.Invocations) != 0 {
			t.Errorf("%s: expected no actuation, got %+v", name, rec.Invocations)
		}
	}
}

// --- The producer-contract half of the oracle --------------------------------
//
// The only in-process producer of a unit-scoped restart is
// System::RestartAfterUpdate#enqueue_restart!, which names
// RestartAfterUpdate.unit_name(target.id, service) =
// "powernode-#{module_id}-#{service_name}.service" for a module ATTACHED to the
// node — i.e. exactly the unit lifecycle.AttachServices materialised for it.
// So the acceptance set is generated here the same way it is generated on a
// node: by lifecycle.AttachServicesMode over the manifest's services, and the
// task names lifecycle.UnitName(...) — never a hand-written literal.
func TestLifecycleAcceptsEveryUnitLifecycleItselfGenerated(t *testing.T) {
	lifecycleUnitDir(t)
	// A System::NodeModule primary key (UUIDv7), the shape every attached
	// module carries; the literal is the one tasks_restart_scope_spec.rb
	// submits.
	moduleID := "019f7cb5-3858-7caa-aa9f-51629dc8e573"
	// Service names taken from the `services:` entries of shipped manifests:
	// powernode-hub-backend (rails), powernode-hub-worker (sidekiq,
	// worker-web), node-exporter (node-exporter), log-forwarder-vector
	// (vector), reverse-proxy-traefik (traefik, restore-dynamic). Enumerating
	// every `services:` entry across modules/*/manifest.yaml yields 21 names
	// (bootstrap, breakglass, caddy, claude, credential, executor, mcp-proxy,
	// mcp-register, node-exporter, pg-replica, postgres, provision, qga,
	// rails, redis, restore-dynamic, runner, sidekiq, traefik, vector,
	// worker-web): a dash is the only non-letter character any of them
	// carries, and the dashed ones are what make the prefix/suffix rules
	// non-trivial.
	services := []manifest.Service{
		{Name: "rails", StartCommand: "/usr/bin/true"},
		{Name: "sidekiq", StartCommand: "/usr/bin/true"},
		{Name: "worker-web", StartCommand: "/usr/bin/true"},
		{Name: "node-exporter", StartCommand: "/usr/bin/true"},
		{Name: "restore-dynamic", StartCommand: "/usr/bin/true"},
		{Name: "vector", StartCommand: "/usr/bin/true"},
		{Name: "traefik", StartCommand: "/usr/bin/true"},
	}
	if _, err := lifecycle.AttachServicesMode(context.Background(), &mount.RecorderRunner{}, moduleID, services, lifecycle.RootModeNative); err != nil {
		t.Fatalf("attach: %v", err)
	}

	for _, svc := range services {
		unit := lifecycle.UnitName(moduleID, svc.Name)
		rec := &mount.RecorderRunner{}
		h := &LifecycleHandler{deps: tasks.Dependencies{MountRunner: rec}, verb: systemd.Restart}
		res, err := h.Execute(context.Background(), lifecycleTask(map[string]any{"scope": "unit", "unit": unit}))
		if err != nil {
			t.Fatalf("%s: refused a unit lifecycle itself generated: %v", unit, err)
		}
		if res["unit"] != unit || res["verb"] != "restart" {
			t.Errorf("%s: unexpected result %+v", unit, res)
		}
		if len(rec.Invocations) != 1 || rec.Invocations[0].Name != "systemctl" ||
			len(rec.Invocations[0].Args) != 2 || rec.Invocations[0].Args[0] != "restart" || rec.Invocations[0].Args[1] != unit {
			t.Errorf("%s: expected exactly `systemctl restart %s`, got %+v", unit, unit, rec.Invocations)
		}
	}

	// The Ruby producer's format is an independent copy of lifecycle.UnitName;
	// pin the two against the literal the operator-facing spec submits so a
	// drift on either side is a red test here, not a refused restart in prod.
	want := "powernode-019f7cb5-3858-7caa-aa9f-51629dc8e573-rails.service"
	if got := lifecycle.UnitName(moduleID, "rails"); got != want {
		t.Errorf("lifecycle.UnitName drifted from RestartAfterUpdate.unit_name: got %q want %q", got, want)
	}
}

// The prefix and suffix the handler requires are the two fixed halves of
// lifecycle.UnitName's format. Pinned by construction against the generator,
// not by inspection of its source.
func TestManagedUnitShapeMatchesLifecycleGenerator(t *testing.T) {
	if got, want := lifecycle.UnitName("m", "s"), managedUnitPrefix+"m-s"+managedUnitSuffix; got != want {
		t.Fatalf("lifecycle.UnitName(%q, %q) = %q; the handler's prefix/suffix expect %q", "m", "s", got, want)
	}
}

// The idempotency short-circuit still works for an accepted unit — validation
// sits in front of it, not instead of it.
func TestLifecycleStartShortCircuitsOnlyForAnAcceptedUnit(t *testing.T) {
	dir := lifecycleUnitDir(t)
	unit := lifecycle.UnitName("019f7cb5-3858-7caa-aa9f-51629dc8e573", "rails")
	writeUnitFile(t, dir, unit)
	rec := &mount.RecorderRunner{StubOutput: map[string][]byte{"systemctl is-active " + unit: []byte("active\n")}}
	h := &LifecycleHandler{deps: tasks.Dependencies{MountRunner: rec}, verb: systemd.Start}
	res, err := h.Execute(context.Background(), lifecycleTask(map[string]any{"unit": unit}))
	if err != nil {
		t.Fatal(err)
	}
	if res["status"] != "already_active" {
		t.Errorf("expected already_active, got %+v", res)
	}
	if len(rec.Invocations) != 1 {
		t.Errorf("expected only the is-active probe, got %+v", rec.Invocations)
	}
}
