# frozen_string_literal: true

module Sdwan
  module Executors
    # Propose a cross-instance federation peer. Driven by
    # FederationPeersController#create through Ai::AutonomyGate (federation
    # peering is always approval-gated).
    #
    # Phase 3a: emit a single-use acceptance token at propose time so the
    # accepting-side operator has a secret to paste into the handshake —
    # mirrors Ai::Tools::SdwanTool#propose_federation_peer's
    # `generate_token: true` path. The plaintext token is returned EXACTLY
    # ONCE (only its digest + expiry are persisted on the peer) so the
    # proposing operator can copy it out-of-band to the peer operator.
    #
    # The token is generated by default. Pass attributes[:generate_token]
    # = false to opt out (e.g. a peer that will be activated via a
    # different trust path). attributes[:token_ttl_seconds] overrides the
    # 7-day default expiry.
    class ProposeFederationPeer < ::System::Executors::Base
      # Single source of this action's autonomy category (IMP-249e01a804e5).
      # Every gate site — the REST controller and Ai::Tools::SdwanTool — reads
      # it from here rather than carrying its own copy, and
      # spec/services/sdwan/executors/action_category_coherence_spec.rb pins the
      # seeded policy row and the engine registration to it.
      ACTION_CATEGORY = "sdwan.federation_peer_propose"

      protected

      def perform
        attributes = attrs
        generate_token = attributes.delete(:generate_token) != false
        ttl_seconds = (attributes.delete(:token_ttl_seconds) || 7.days.to_i).to_i

        peer = ::System::FederationPeer.create!(
          attributes.merge(account: account, status: "proposed")
        )

        result = { federation_peer_id: peer.id }

        if generate_token
          plaintext = peer.generate_acceptance_token!(ttl_seconds: ttl_seconds)
          result[:acceptance_token_plaintext]  = plaintext
          result[:acceptance_token_expires_at] = peer.reload.acceptance_token_expires_at&.iso8601
          result[:note] = "Store the acceptance token immediately — it is shown EXACTLY ONCE. " \
                          "The accepting-side operator pastes this into the federation handshake."
        end

        result
      end

      def summarize = "Propose cross-instance federation with #{params.dig(:attributes, :remote_instance_url) || params.dig(:attributes, :remote_endpoint)}"
      def impact    = "Initiates a federation handshake with a remote Powernode instance and mints a single-use acceptance token"
    end
  end
end
