# frozen_string_literal: true

module Api
  module V1
    module System
      module Webhooks
        # Inbound webhook from the build-package-module.yaml CI workflow.
        # The workflow signs each callback with HMAC-SHA256 over the raw
        # body using the closure-specific secret generated by
        # ModuleBuildDispatchService.generate_webhook_secret. We verify
        # the signature and route to PackageBuildWebhookService.
        #
        # Per `feedback_webhook_receivers` in CLAUDE.md: inbound webhooks
        # return 200/202 on processing errors, NEVER 500 (avoids provider
        # retry storms). We log internally and return 202 with an error
        # field for the CI workflow to record but not retry on.
        class PackageBuildController < ApplicationController
          include ::System::Webhooks::HmacVerification

          skip_before_action :authenticate_request, raise: false
          skip_before_action :verify_authenticity_token, raise: false

          def receive
            raw_body = request.raw_post
            sig = request.headers["X-Powernode-Signature"]

            unless verify_signature(raw_body, sig)
              render_error("Signature verification failed", status: :unauthorized)
              return
            end

            payload = JSON.parse(raw_body)
            result = ::System::PackageBuildWebhookService.call(payload: payload)

            if result.success
              render_success(
                {
                  artifacts_created: result.artifacts_created,
                  versions_created:  result.versions_created,
                  modules_updated:   result.modules_updated
                },
                status: :accepted
              )
            else
              # Return 202 even on processing errors per webhook-receiver
              # rule — log internally, surface for CI workflow visibility.
              Rails.logger.error("[PackageBuildWebhook] processing errors: #{result.errors.inspect}")
              render_success(
                {
                  ok:     false,
                  errors: result.errors
                },
                status: :accepted
              )
            end
          rescue JSON::ParserError => e
            render_error("Invalid JSON: #{e.message}", status: :bad_request)
          rescue ::System::PackageBuildWebhookService::WebhookError => e
            render_error("Webhook validation error: #{e.message}", status: :unprocessable_content)
          rescue StandardError => e
            # Catch-all for unexpected PROCESSING failures. Per the platform
            # webhook-receiver rule, return 202 (NEVER 500) so the CI workflow
            # records the failure without retry-storming. Auth/signature
            # rejections are handled above (401) and never reach here. Log
            # internally for operator visibility, mirroring GiteaModuleController.
            Rails.logger.error("[PackageBuildWebhook] processing error: #{e.class}: #{e.message}")
            Rails.logger.error(e.backtrace.first(5).join("\n")) if e.backtrace
            render_success(
              {
                ok:    false,
                error: "#{e.class}: #{e.message}"
              },
              status: :accepted
            )
          end

          private

          # Verifies HMAC-SHA256 over the RAW BODY (not just closure_id) using
          # the per-closure secret derived by
          # ModuleBuildDispatchService.webhook_secret_for — the same value the
          # CI workflow signs with. Signing the whole body authenticates the
          # artifact metadata (oci_ref, versions), so a captured signature
          # can't be replayed against a forged body. Header format:
          # "sha256=<hex>" (mirrors the disk-image webhook + Gitea/GitHub).
          #
          # Fails closed: when no server-side secret is configured (prod, env
          # var unset) webhook_secret_for returns nil and we REJECT, rather
          # than trusting a publicly-known committed default.
          def verify_signature(body, signature)
            return false if signature.blank?

            closure_id = JSON.parse(body)["closure_id"] rescue nil
            return false if closure_id.blank?

            secret = ::System::ModuleBuildDispatchService.webhook_secret_for(closure_id)
            return false if secret.blank? # fail closed — never trust a default

            # Constant-time HMAC compare via the shared concern (tolerates a
            # leading "sha256=" prefix; false on malformed/length-mismatch).
            secure_match?(hmac_hex(secret, body), signature)
          rescue StandardError
            false
          end
        end
      end
    end
  end
end
