package security

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// WriteUserNamespaceDropIn renders a systemd drop-in that sets the unit's
// `PrivateUsers=` directive, mapping (or explicitly NOT mapping) the
// module's processes into a private user namespace. Mirrors
// WriteCapabilityDropIn / WriteSeccompDropIn — same drop-in dir layout,
// same path-traversal guards, same atomic write semantics.
//
// File path: /etc/systemd/system/<unit>.d/userns.conf
//
// Drop-in shape (per systemd.exec(5)):
//
//	[Service]
//	PrivateUsers=yes   # or no
//
// A deterministic value is ALWAYS emitted (never omitted) so the documented
// Policy.UserNamespace default (true) is actually enforced and the file is
// idempotent:
//   - enabled  -> PrivateUsers=yes : the unit runs in a private user
//     namespace; UID/GID 0 inside the service maps to an unprivileged host
//     UID/GID, so a compromise can't touch host-owned files.
//   - disabled -> PrivateUsers=no  : explicit host user namespace, required
//     by workloads that need raw socket access / host-UID semantics. Stated
//     explicitly rather than omitted so the posture is auditable.
//
// PrivateUsers= is orthogonal to CapabilityBoundingSet=/SystemCallFilter=
// (capabilities/seccomp drop-ins): systemd composes all three. PrivateUsers=
// only changes the UID/GID mapping namespace; it does not relax or override
// the capability bounding set or seccomp filter, so writing this drop-in
// alongside the others never weakens them.
//
// Caller must invoke systemctl daemon-reload after writing drop-ins.
func WriteUserNamespaceDropIn(unit string, enabled bool) error {
	if unit == "" {
		return errors.New("WriteUserNamespaceDropIn: empty unit")
	}
	if strings.ContainsAny(unit, "/\\\x00") || strings.Contains(unit, "..") {
		return errors.New("WriteUserNamespaceDropIn: invalid unit name (path traversal)")
	}
	if strings.HasPrefix(unit, "-") {
		return errors.New("WriteUserNamespaceDropIn: invalid unit name (leading dash)")
	}

	value := "no"
	if enabled {
		value = "yes"
	}

	dropInDir := filepath.Join(systemdDropInRoot, unit+".d")
	if err := os.MkdirAll(dropInDir, 0o755); err != nil {
		return fmt.Errorf("WriteUserNamespaceDropIn: mkdir %s: %w", dropInDir, err)
	}

	var body strings.Builder
	body.WriteString("# Auto-generated by powernode-agent. User-namespace isolation\n")
	body.WriteString("# (PrivateUsers=) set per the module's manifest security policy.\n")
	body.WriteString("# DO NOT EDIT BY HAND — overwritten on every reconcile.\n")
	body.WriteString("\n[Service]\n")
	body.WriteString("PrivateUsers=")
	body.WriteString(value)
	body.WriteString("\n")

	dropInPath := filepath.Join(dropInDir, "userns.conf")
	tmp := dropInPath + ".tmp"
	if err := os.WriteFile(tmp, []byte(body.String()), 0o644); err != nil {
		return fmt.Errorf("WriteUserNamespaceDropIn: write tmp: %w", err)
	}
	if err := os.Rename(tmp, dropInPath); err != nil {
		_ = os.Remove(tmp)
		return fmt.Errorf("WriteUserNamespaceDropIn: rename: %w", err)
	}
	return nil
}
