#!/usr/bin/env bash
# Run the cloud-provider adapter specs WITH their optional SDK gems bundled.
#
# Why this exists: the aws/openstack provider specs self-skip (RSpec `pending`)
# when their optional SDK gem isn't loadable — their `before` blocks stub
# `Aws::EC2::Client` / `Fog::OpenStack::Compute`, which don't exist under the
# core bundle (those gems are intentionally omitted; see
# server/powernode_system.gemspec). So under the default bundle ~64 provider
# examples skip, and a "green" run there does NOT exercise AwsProvider /
# OpenStackProvider — provider regressions (e.g. run_instances ClientToken /
# tag_specifications, connect/read timeouts) slip through. This script layers
# those gems onto the core bundle via a throwaway supplementary Gemfile and
# runs the provider suite for real.
#
# GcpProvider (mocked clients) and AzureProvider (hand-rolled Faraday client)
# need no SDK gem and already run under the default bundle — they are included
# here only so this is a single "run the whole provider suite" entry point.
#
# Usage (assumes extensions/system/ is mounted inside powernode-platform/):
#   bash extensions/system/scripts/test-provider-gems.sh                 # all provider specs
#   bash extensions/system/scripts/test-provider-gems.sh <spec paths...> # subset (paths relative to server/)
#
# Wired into CI by the `provider-specs` job in .gitea/workflows/ci.yaml.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PLATFORM_SERVER="$(cd "${EXT_ROOT}/../../server" 2>/dev/null && pwd || true)"

if [[ -z "${PLATFORM_SERVER}" || ! -f "${PLATFORM_SERVER}/Gemfile" ]]; then
  echo "FATAL: cannot locate parent platform server/ (expected at \$EXT_ROOT/../../server)"
  echo "       This script assumes extensions/system/ is mounted inside powernode-platform/."
  exit 1
fi

# The supplementary Gemfile MUST live next to the core Gemfile: it does
# `eval_gemfile "Gemfile"`, and the core Gemfile resolves extension path gems
# with paths relative to ITS own directory (server/). A supplementary Gemfile
# in any other directory would break that resolution.
PROVIDER_GEMS_GEMFILE="${PLATFORM_SERVER}/.provider-gems.gemfile"

cleanup() {
  rm -f "${PROVIDER_GEMS_GEMFILE}" "${PROVIDER_GEMS_GEMFILE}.lock"
}
trap cleanup EXIT

cat > "${PROVIDER_GEMS_GEMFILE}" <<'EOF'
# frozen_string_literal: true
# GENERATED by extensions/system/scripts/test-provider-gems.sh — do not edit or commit.
# Layers the optional cloud-provider SDK gems onto the core platform bundle so
# the aws/openstack provider specs execute instead of self-skipping.
eval_gemfile "Gemfile"
gem "aws-sdk-ec2", "~> 1"
gem "fog-openstack", "~> 1"
EOF

cd "${PLATFORM_SERVER}"

# Default: the four cloud-provider spec files. Caller may pass a subset.
DEFAULT_SPECS=(
  "../extensions/system/server/spec/services/system/providers/aws_provider_spec.rb"
  "../extensions/system/server/spec/services/system/providers/azure_provider_spec.rb"
  "../extensions/system/server/spec/services/system/providers/gcp_provider_spec.rb"
  "../extensions/system/server/spec/services/system/providers/open_stack_provider_spec.rb"
)
if [[ "$#" -gt 0 ]]; then
  SPECS=("$@")
else
  SPECS=("${DEFAULT_SPECS[@]}")
fi

# Resolve the supplementary bundle in a NON-frozen, NON-deployment install:
# its lock is throwaway + never committed, and the floated SDK gems must
# resolve fresh each run regardless of any frozen/deployment config the core
# `bundle install` left in .bundle/config.
export BUNDLE_GEMFILE="${PROVIDER_GEMS_GEMFILE}"
export BUNDLE_FROZEN=false
export BUNDLE_DEPLOYMENT=false

# Seed the supplementary lock from the committed core lock so `bundle install`
# only resolves the two ADDED SDK gems (+ their deps) and leaves every core gem
# pinned to the version the rest of CI / production uses. Without this seed the
# non-frozen install re-resolves the WHOLE graph against the Gemfile's loose
# constraints, so an unrelated upstream gem release could flip this lane
# red/green or exercise the provider code against versions no one else runs.
if [[ -f "${PLATFORM_SERVER}/Gemfile.lock" ]]; then
  cp "${PLATFORM_SERVER}/Gemfile.lock" "${PROVIDER_GEMS_GEMFILE}.lock"
fi

echo "==> Installing provider SDK gems (aws-sdk-ec2, fog-openstack) onto the core bundle"
bundle install --quiet

echo "==> Running provider specs WITH SDK gems bundled (aws/openstack no longer skip)"
bundle exec rspec --format progress "${SPECS[@]}"
